# Generated by Django 5.2.7 on 2025-10-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logedin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
