# Generated by Django 5.2.7 on 2025-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('details', models.CharField()),
                ('create', models.TimeField()),
                ('owner', models.IntegerField()),
            ],
        ),
    ]
